### ISSUE TITLE
Jedis driver support

### ISSUE THREAD

**Issue by MarkBramnik** [mokies/ratelimitj#5]
Hi, Any plans to support [Jedis](https://github.com/xetorthio/jedis) ?
Many projects don't use letucce and work with Jedis instead.
Thanks

**Comment by mokies** [comment]
Hey Mark,

This request has come up before from colleagues. They have a project that is using Jedis or Reddison and want to keep a single driver in the code base, which is fair question.

Is it really a problem to use multiple Redis drivers in a single code base? Traditionally I would have never considered using multiple relational database drivers in a single code base but I feel the different Redis drivers are richer than a tranditional DB driver and offer competing rich functionality. For example I have used the combination of Jedis & Reddison in a single code base because Jedis was introduced first and we wanted to utilise Reddison's implementation of the Red Lock algorithm not offered by Jedis.

I understand that Lettuce is newer and less widely adopted Redis driver but it's asynchronous foundation is very useful for some of the more advanced rate limiter patterns that I am looking to implement.

So to answer your question, no probably not unless there is a large demand. I would encourage you to consider running with multiple 'drivers' in your codebase. Because of Lettuce's non blocking design it will only use a single Redis connection.   

Cheers,
Craig

**Comment by jimmymic** [comment]
It is the first stumbling block I have come across using this library - possible/simple to support both maybe?

I like the look of the library but not sure I can convince the team that having multiple drivers is a good idea.

Thanks

**Comment by mokies** [comment]
This would not be simple to support as RateLimitJ is built on an asynchronous/reactive foundation which is only supported by Lettuce.
